version: '3.8'

services:
  web:
    build: .
    container_name: flask-web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./certs:/etc/letsencrypt:ro
  #   depends_on:
  #     - web
